#!/usr/bin/env bash
# .warden/run.sh - warden engine v0.1.0
# Generated by /warden:design. Project-owned; modify freely.
#
# Usage:
#   bash .warden/run.sh                     # all plans, in phase order
#   bash .warden/run.sh 01-boot             # a specific plan (by basename match)
#   bash .warden/run.sh phase:api           # all plans in one phase
#   bash .warden/run.sh --strict            # abort suite on first failure
#
# Plan contract:
#   - Each plan is a markdown file with one or more fenced bash blocks.
#   - Multi-block plans share variables; blocks are concatenated before exec.
#   - Plans `source "$WARDEN_LIB/assert.sh"` and call warden_pass / warden_fail / warden_skip.
#   - Each assertion emits a structured `WARDEN_RESULT <kind> <id>` line for counting,
#     plus a human-readable line for log readers.

set -uo pipefail

WARDEN_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$WARDEN_DIR/.." && pwd)"
WARDEN_LIB="$WARDEN_DIR/lib"
PLANS_DIR="$WARDEN_DIR/plans"
LOGS_DIR="$WARDEN_DIR/logs"
RUNS_DIR="$WARDEN_DIR/runs"

mkdir -p "$LOGS_DIR" "$RUNS_DIR"

# Default config values (overridden by warden.config.sh if present)
WARDEN_PHASES=()
ENV_FILES=(.env)
PREFLIGHT=()
RUNTIME_CHECKS=()

# Source project config (sets WARDEN_PHASES, ENV_FILES, PREFLIGHT, RUNTIME_CHECKS, service URLs)
if [[ -f "$WARDEN_DIR/warden.config.sh" ]]; then
  # shellcheck disable=SC1091
  source "$WARDEN_DIR/warden.config.sh"
fi

# Result counting helper
# shellcheck disable=SC1091
source "$WARDEN_LIB/parse.sh"

WARDEN_RUN_ID="$(date +%Y%m%dT%H%M%S)"
STRICT=0

ARGS=()
for arg in "$@"; do
  case "$arg" in
    --strict) STRICT=1 ;;
    *) ARGS+=("$arg") ;;
  esac
done

PLAN_FILES=()

discover_phase_plans() {
  local phase="$1"
  local phase_dir="$PLANS_DIR/$phase"
  [[ -d "$phase_dir" ]] || return 0
  while IFS= read -r f; do PLAN_FILES+=("$f"); done < <(find "$phase_dir" -maxdepth 1 -name "*.md" | sort)
}

discover_root_plans() {
  [[ -d "$PLANS_DIR" ]] || return 0
  while IFS= read -r f; do PLAN_FILES+=("$f"); done < <(find "$PLANS_DIR" -maxdepth 1 -name "*.md" | sort)
}

discover_all_plans() {
  [[ -d "$PLANS_DIR" ]] || return 0
  while IFS= read -r f; do PLAN_FILES+=("$f"); done < <(find "$PLANS_DIR" -name "*.md" | sort)
}

resolve_arg() {
  local arg="$1"
  if [[ "$arg" == phase:* ]]; then
    discover_phase_plans "${arg#phase:}"
    return
  fi
  while IFS= read -r f; do
    PLAN_FILES+=("$f")
  done < <(find "$PLANS_DIR" \( -name "${arg}.md" -o -name "${arg}-*.md" \) | sort)
}

if [[ ${#ARGS[@]} -gt 0 ]]; then
  for arg in "${ARGS[@]}"; do
    resolve_arg "$arg"
  done
elif [[ ${#WARDEN_PHASES[@]} -gt 0 ]]; then
  discover_root_plans
  for phase in "${WARDEN_PHASES[@]}"; do
    discover_phase_plans "$phase"
  done
else
  discover_all_plans
fi

if [[ ${#PLAN_FILES[@]} -eq 0 ]]; then
  echo "warden: no plans found"
  exit 0
fi

# Pre-flight (warn-only unless --strict)
if [[ ${#PREFLIGHT[@]} -gt 0 ]]; then
  for cmd in "${PREFLIGHT[@]}"; do
    if ! eval "$cmd" >/dev/null 2>&1; then
      echo "warden: pre-flight failed: $cmd" >&2
      if [[ $STRICT -eq 1 ]]; then
        exit 1
      fi
    fi
  done
fi

# Runtime checks (always warn-only; plans that need the tool will fail naturally)
if [[ ${#RUNTIME_CHECKS[@]} -gt 0 ]]; then
  for cmd in "${RUNTIME_CHECKS[@]}"; do
    if ! eval "$cmd" >/dev/null 2>&1; then
      echo "warden: runtime missing: $cmd" >&2
    fi
  done
fi

echo ""
echo "======================================================================"
echo "  warden run $WARDEN_RUN_ID"
echo "  plans: ${#PLAN_FILES[@]}"
[[ $STRICT -eq 1 ]] && echo "  mode: strict"
echo "======================================================================"
echo ""

TOTAL_PASS=0
TOTAL_FAIL=0
TOTAL_SKIP=0
RESULTS=()

finalize() {
  echo ""
  echo "======================================================================"
  echo "  Total: $TOTAL_PASS passed, $TOTAL_FAIL failed, $TOTAL_SKIP skipped"
  echo "======================================================================"

  {
    echo "# warden run $WARDEN_RUN_ID"
    echo ""
    echo "Total: $TOTAL_PASS passed, $TOTAL_FAIL failed, $TOTAL_SKIP skipped"
    echo ""
    echo "## Plans"
    echo ""
    for r in "${RESULTS[@]}"; do
      echo "- $r"
    done
  } > "$RUNS_DIR/${WARDEN_RUN_ID}.md"
}

run_plan() {
  local md="$1"
  local name script log
  name="$(basename "$md" .md)"
  log="$LOGS_DIR/${name}-${WARDEN_RUN_ID}.log"
  script="$(sed -n '/^```bash$/,/^```$/{ /^```/d; p; }' "$md")"

  if [[ -z "$script" ]]; then
    echo "  o $name (no bash block, skipped)"
    TOTAL_SKIP=$((TOTAL_SKIP + 1))
    RESULTS+=("SKIP $name (no bash block)")
    return
  fi

  echo "> $name"

  export WARDEN_DIR WARDEN_LIB WARDEN_RUN_ID PROJECT_ROOT
  export WARDEN_LOG="$log"
  export WARDEN_PLAN_NAME="$name"

  bash -c "$script" > "$log" 2>&1
  local exit_code=$?

  local plan_pass plan_fail plan_skip
  plan_pass=$(warden_count_results "$log" pass)
  plan_fail=$(warden_count_results "$log" fail)
  plan_skip=$(warden_count_results "$log" skip)

  TOTAL_PASS=$((TOTAL_PASS + plan_pass))
  TOTAL_FAIL=$((TOTAL_FAIL + plan_fail))
  TOTAL_SKIP=$((TOTAL_SKIP + plan_skip))

  if [[ $exit_code -eq 0 && $plan_fail -eq 0 ]]; then
    echo "  PASS $name ($plan_pass passed, $plan_skip skipped)"
    RESULTS+=("PASS $name ($plan_pass passed, $plan_skip skipped)")
  else
    echo "  FAIL $name ($plan_pass passed, $plan_fail failed, $plan_skip skipped)"
    echo "    log: $log"
    RESULTS+=("FAIL $name ($plan_pass passed, $plan_fail failed, $plan_skip skipped)")
    if [[ $STRICT -eq 1 ]]; then
      finalize
      exit 1
    fi
  fi
}

for plan in "${PLAN_FILES[@]}"; do
  run_plan "$plan"
done

finalize

if [[ $TOTAL_FAIL -gt 0 ]]; then
  exit 1
fi
exit 0
